export type FallbackLevel = {
  id: string;
  slug: string;
  rank: number;
  name: string;
  originalName: string;
  gdLevelId: string;
  publisher: string;
  nerfCreator: string;
  verifier: string;
  thumbnailUrl: string;
  showcaseUrl: string;
  status: "RANKED" | "LEGACY";
  difficulty: string;
  points: number;
  description: string;
  recordCount: number;
};

export const FALLBACK_RANKED_LEVELS: FallbackLevel[] = [
  {
    id: "cmpvcscks000004l14bekv378",
    slug: "kocmoc-unleashed-uldm-nerfed-mpvcscja",
    rank: 1,
    name: "Kocmoc Unleashed ULDM Nerfed",
    originalName: "Kocmoc Unleashed ULDM",
    gdLevelId: "141565850",
    publisher: "cattwgdx",
    nerfCreator: "cattwgdx",
    verifier: "cattwgdx",
    thumbnailUrl: "/thumbnails/levels/kocmoc-unleashed-uldm-nerfed-mpvcscja.jpg",
    showcaseUrl: "https://www.tiktok.com/@cattw_gd/video/7645766642835655938?is_from_webapp=1&sender_device=pc",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 1000,
    description: "Community-suggested nerfed version of Kocmoc Unleashed ULDM.",
    recordCount: 1,
  },
  {
    id: "cmpvnpo7e000004l3c5v8k92a",
    slug: "amethyst-nerfed-mpvnpo7d",
    rank: 2,
    name: "Amethyst Nerfed",
    originalName: "Amethyst",
    gdLevelId: "123456789",
    publisher: "cattw21",
    nerfCreator: "cattw21",
    verifier: "cattw21",
    thumbnailUrl: "/thumbnails/levels/amethyst-nerfed-mpvnpo7d.jpg",
    showcaseUrl: "https://youtu.be/4FXfZip3tgQ",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 975,
    description: "Nerfed extreme demon version of Amethyst.",
    recordCount: 2,
  },
  {
    id: "cmpvo0bcx000004l6x9a2k81z",
    slug: "tidal-wave-easy-mpvo0bcx",
    rank: 3,
    name: "Tidal Wave Easy",
    originalName: "Tidal Wave",
    gdLevelId: "135792468",
    publisher: "cattw21",
    nerfCreator: "cattw21",
    verifier: "cattw21",
    thumbnailUrl: "/thumbnails/levels/tidal-wave-easy-mpvo0bcx.jpg",
    showcaseUrl: "https://youtu.be/K0ZT4FMoNvo?list=RDK0ZT4FMoNvo",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 950,
    description: "Accessible nerfed version of Tidal Wave.",
    recordCount: 1,
  },
  {
    id: "cmtkf8vnr000004jnd2a883gq",
    slug: "andromeda-nerfed-mtkf8vnq",
    rank: 4,
    name: "Andromeda Nerfed",
    originalName: "Andromeda",
    gdLevelId: "120925053",
    publisher: "Insxne97",
    nerfCreator: "Togatta",
    verifier: "Sambor",
    thumbnailUrl: "/thumbnails/levels/andromeda-nerfed-mtkf8vnq.jpg",
    showcaseUrl: "https://medal.tv/games/geometry-dash/clips/nrGRI4K792z3Esew0?invite=cr-MSxVcmcsNTc2MDY2MzM2",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 925,
    description: "Harder than nerfed kocmoc",
    recordCount: 1,
  },
  {
    id: "cmshyw5a1000404l2cxc8pkoa",
    slug: "kocmoc-nerfed-mshyw58z",
    rank: 5,
    name: "KOCMOC NERFED",
    originalName: "Kocmoc",
    gdLevelId: "91059275",
    publisher: "cherryteam",
    nerfCreator: "AkayukiGD",
    verifier: "Sambor",
    thumbnailUrl: "/thumbnails/levels/kocmoc-nerfed-mshyw58z.jpg",
    showcaseUrl: "https://medal.tv/games/geometry-dash/clips/mIKdo8OSIezerNx_W?invite=cr-MSxCWTUsNTc2MDY2MzM2&v=108",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 900,
    description: "I dont actually know if im the verifier i just have footage of me beating it, also AkayukiGD has so many more nerfed levels i would love them to be put on this list :)",
    recordCount: 1,
  },
  {
    id: "cmtaf0w0j000004l57zo05pvu",
    slug: "acheron-nerfed-mtaf0vwx",
    rank: 6,
    name: "Acheron Nerfed",
    originalName: "Acheron",
    gdLevelId: "106966671",
    publisher: "Riot",
    nerfCreator: "AkayukiGD",
    verifier: "Sambor",
    thumbnailUrl: "/thumbnails/levels/acheron-nerfed-mtaf0vwx.jpg",
    showcaseUrl: "https://medal.tv/games/geometry-dash/clips/nuYXGrqWnF-ipai9V?invite=cr-MSx0YWwsNTc2MDY2MzM2",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 880,
    description: "Fun aff level",
    recordCount: 1,
  },
  {
    id: "cmt3akbeq000204ldbiu1f5pq",
    slug: "sakupen-circles-nerf-mt3akbcy",
    rank: 7,
    name: "Sakupen Circles Nerf",
    originalName: "Sakupen Circles",
    gdLevelId: "108071188",
    publisher: "Diamond",
    nerfCreator: "AkayukiGD",
    verifier: "Sambor",
    thumbnailUrl: "/thumbnails/levels/sakupen-circles-nerf-mt3akbcy.jpg",
    showcaseUrl: "https://medal.tv/games/geometry-dash/clips/ncLvRyHq6p8CWzkWM?invite=cr-MSxZTmUsNTc2MDY2MzM2",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 860,
    description: "I think its hard or very easy insane demon.",
    recordCount: 1,
  },
  {
    id: "cmt90m8bc000004jma7gqk34l",
    slug: "silent-clubstep-easy-mt90m89e",
    rank: 8,
    name: "silent clubstep easy",
    originalName: "silent clubstep",
    gdLevelId: "147696187",
    publisher: "alalrbw",
    nerfCreator: "alalrbw",
    verifier: "alalrbw",
    thumbnailUrl: "/thumbnails/levels/silent-clubstep-easy-mt90m89e.jpg",
    showcaseUrl: "https://www.youtube.com/watch?v=K0dgE2ICa-w",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 840,
    description: "i made one part auto since i couldn't nerf it in an way. made gaps bigger and added more space",
    recordCount: 3,
  },
  {
    id: "cmt7k1g3d000604jr0v4480sa",
    slug: "nerfed-sakupen-hell-mt7k1g21",
    rank: 9,
    name: "Nerfed Sakupen Hell",
    originalName: "Sakupen Hell",
    gdLevelId: "147592555",
    publisher: "alalrbw",
    nerfCreator: "alalrbw",
    verifier: "alalrbw",
    thumbnailUrl: "/thumbnails/levels/nerfed-sakupen-hell-mt7k1g21.jpg",
    showcaseUrl: "https://www.youtube.com/watch?v=Z5T7l6NTQwo",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 820,
    description: "im confused on what this means but ill just take it as you asking me what i changed. gaps are more wide and certain clicks are blue pads instead of clicks",
    recordCount: 3,
  },
  {
    id: "cmpvnhe49000004jv0zto5i5q",
    slug: "thinking-space-ii-easy-mpvnhe2z",
    rank: 10,
    name: "Thinking Space II Easy",
    originalName: "Thinking Space II",
    gdLevelId: "127132917",
    publisher: "VIrTIX10",
    nerfCreator: "VIrTIX10",
    verifier: "Ploggix",
    thumbnailUrl: "/thumbnails/levels/thinking-space-ii-easy-mpvnhe2z.jpg",
    showcaseUrl: "https://youtu.be/piCzVYS2Zm4",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 800,
    description: "Community-suggested nerfed version of Thinking Space II.",
    recordCount: 1,
  },
  {
    id: "cmpvoceha000004lawr4sjl34",
    slug: "boobawamba-nerfed-mpvoceeh",
    rank: 11,
    name: "BOOBAWAMBA Nerfed",
    originalName: "BOOBAWAMBA",
    gdLevelId: "117257024",
    publisher: "RealRetyol",
    nerfCreator: "RealRetyol",
    verifier: "Han Xin",
    thumbnailUrl: "/thumbnails/levels/boobawamba-nerfed-mpvoceeh.jpg",
    showcaseUrl: "https://youtu.be/sj22eAqjJoY?list=RDsj22eAqjJoY",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 785,
    description: "Gameplay is same portals and speed portals. instead of darkness like in the original level you can see in the nerfed version.",
    recordCount: 1,
  },
  {
    id: "cmshyd43f000204kvgsmjs7ta",
    slug: "nerfed-cataclysm-mshyd42i",
    rank: 12,
    name: "Nerfed Cataclysm",
    originalName: "Cataclysm",
    gdLevelId: "30861969",
    publisher: "TarReX",
    nerfCreator: "TarReX",
    verifier: "TarReX",
    thumbnailUrl: "/thumbnails/levels/nerfed-cataclysm-mshyd42i.jpg",
    showcaseUrl: "https://youtu.be/hjdkeXOAjs4",
    status: "RANKED",
    difficulty: "EXTREME",
    points: 770,
    description: "Nerfed Cataclysm doesnt work at all with original cataclysm macro",
    recordCount: 10,
  },
];
